default['sample']['dir'] = '/home/ec2-user/dir'
default['sample']['dbname']='db3'
default['sample']['portnumber']='8080'
default['sample']['url']='www.mybluemix.net'
default['task']['dir'] = '/home/ec2-user/task'
default['task']['portnumber'] = '8443'
default['task']['maximumthreads'] = '150'
